### ISSUE TITLE
double check for mounted overlay-root filesystems before umount

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#174] opened 2016-01-12 20:18 UTC
In some rare cases you might start with a dirty system:

```
==> Cleaning up ...
  -> Deleting chroot 'kde-image'...
  -> Deleting chroot 'root-image'...
rm: cannot remove '/var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/root-image': Device or resource busy
rm: cannot remove '/var/lib/manjaro-tools/buildiso/kde-minimal/x86_64/root-image': Device or resource busy
```

we should find a way to detect and prevent it ...

**Comment by udeved** [comment] 2016-01-12 20:24
I think the cause was the filesystem conflict previous build.
So we need error handling when overlay gets copied my guess.

**Comment by udeved** [comment] 2016-02-14 22:21
~~~
Enter a selection (default=all): 
warning: skipping target: openbox
resolving dependencies...
warning: cannot resolve "manjaro-openbox-minimal", a dependency of "manjaro-lxqt-minimal-settings"
:: The following package cannot be upgraded due to unresolvable dependencies:
      manjaro-lxqt-minimal-settings

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: manjaro-lxqt-minimal-settings: requires manjaro-openbox-minimal
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
  -> overlayfs: unmount lxqt-image
==> ERROR: Exit make_image_custom
~~~

I have had a typo in the depends of the OB package.
It cleanly unmounts everything for me.

/etc/mtab has no images mounted after error.

**Closed** 2016-02-25 19:57 UTC
Labels: buildiso
